#!/usr/bin/env npx tsx
/**
 * Generate Trail Map — Creates USER-JOURNEYS.md from checkpoints.json
 *
 * Reads structured checkpoint state and generates a Markdown trail map
 * with Mermaid diagrams and status tables.
 *
 * Usage:
 *   npx tsx scripts/generate-map.ts
 *   npx tsx scripts/generate-map.ts --output docs/test-coverage/USER-JOURNEYS.md
 */

import * as fs from 'fs';

interface CheckpointState {
  id: string;
  description: string;
  status: 'pass' | 'fail' | 'skip' | 'wip' | 'uncharted';
  lastRun: string;
  durationMs?: number;
  error?: string;
}

interface JourneyState {
  checkpoints: Record<string, CheckpointState>;
}

interface CoverageState {
  lastUpdated: string;
  journeys: Record<string, JourneyState>;
}

const STATUS_ICONS: Record<string, string> = {
  pass: '✅',
  fail: '❌',
  skip: '⏭️',
  wip: '🔄',
  uncharted: '❌',
};

const STATUS_NAMES: Record<string, string> = {
  pass: 'Cleared',
  fail: 'Blocked',
  skip: 'Skipped',
  wip: 'Scouted',
  uncharted: 'Uncharted',
};

const STATE_FILE = 'checkpoints.json';

function parseArgs(): { output: string } {
  const args = process.argv.slice(2);
  let output = 'USER-JOURNEYS.md';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--output' && args[i + 1]) {
      output = args[++i];
    }
  }

  return { output };
}

function generateMap(state: CoverageState): string {
  const lines: string[] = [];
  const today = new Date().toISOString().split('T')[0];

  lines.push('# Trail Map — User Journeys');
  lines.push('');
  lines.push(`*Last updated: ${today}*`);
  lines.push('');

  // Coverage summary table
  lines.push('## Coverage Summary');
  lines.push('');
  lines.push('| Journey | Coverage | Checkpoints | Last Run |');
  lines.push('|---------|----------|-------------|----------|');

  let globalPassed = 0;
  let globalTotal = 0;

  for (const [journeyName, journey] of Object.entries(state.journeys)) {
    const checkpoints = Object.values(journey.checkpoints);
    const passed = checkpoints.filter((c) => c.status === 'pass').length;
    const total = checkpoints.length;
    const coverage = total > 0 ? Math.round((passed / total) * 100) : 0;
    const lastRun = checkpoints
      .map((c) => c.lastRun)
      .sort()
      .reverse()[0] || '-';

    lines.push(`| ${journeyName.toUpperCase()} | ${coverage}% | ${passed}/${total} | ${lastRun} |`);
    globalPassed += passed;
    globalTotal += total;
  }

  const globalCoverage = globalTotal > 0 ? Math.round((globalPassed / globalTotal) * 100) : 0;
  lines.push('');
  lines.push(`**Total Coverage:** ${globalCoverage}% (${globalPassed}/${globalTotal} checkpoints cleared)`);
  lines.push('');
  lines.push('---');

  // Per-journey sections
  for (const [journeyName, journey] of Object.entries(state.journeys)) {
    const checkpoints = Object.values(journey.checkpoints).sort((a, b) =>
      a.id.localeCompare(b.id, undefined, { numeric: true })
    );

    lines.push('');
    lines.push(`## ${journeyName.toUpperCase()} Journey`);
    lines.push('');

    // Checkpoint table
    lines.push('### Checkpoints');
    lines.push('');
    lines.push('| ID | Checkpoint | Status | Last Run |');
    lines.push('|----|------------|--------|----------|');

    for (const cp of checkpoints) {
      const icon = STATUS_ICONS[cp.status] || '❓';
      lines.push(`| ${cp.id} | ${cp.description || '-'} | ${icon} ${STATUS_NAMES[cp.status] || cp.status} | ${cp.lastRun || '-'} |`);
    }

    lines.push('');
    lines.push('---');
  }

  // Legend
  lines.push('');
  lines.push('## Trail Markers Legend');
  lines.push('');
  lines.push('| Marker | Meaning |');
  lines.push('|--------|---------|');
  lines.push('| ❌ | Uncharted — checkpoint identified, not tested |');
  lines.push('| 🔄 | Scouted — test written, not yet passing |');
  lines.push('| ✅ | Cleared — test passing |');
  lines.push('| ⚠️ | Unstable — flaky test, needs investigation |');
  lines.push('| ⏭️ | Skipped — intentionally not tested |');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by Pathfinder — Marks the trail before others follow.*');
  lines.push('');

  return lines.join('\n');
}

async function main() {
  const { output } = parseArgs();

  console.log('🗺️  Pathfinder Trail Map Generator');

  if (!fs.existsSync(STATE_FILE)) {
    console.log(`   No state file found at ${STATE_FILE}`);
    console.log('   Run coverage update first: npm run test:coverage');
    process.exit(0);
  }

  const state: CoverageState = JSON.parse(fs.readFileSync(STATE_FILE, 'utf-8'));
  const map = generateMap(state);

  fs.writeFileSync(output, map);

  // Count totals
  let totalPassed = 0;
  let totalCheckpoints = 0;
  for (const journey of Object.values(state.journeys)) {
    for (const cp of Object.values(journey.checkpoints)) {
      totalCheckpoints++;
      if (cp.status === 'pass') totalPassed++;
    }
  }
  const coverage = totalCheckpoints > 0 ? Math.round((totalPassed / totalCheckpoints) * 100) : 0;

  console.log(`   Generated: ${output}`);
  console.log(`   Journeys: ${Object.keys(state.journeys).length}`);
  console.log(`   Coverage: ${totalPassed}/${totalCheckpoints} (${coverage}%)`);
}

main().catch((e) => {
  console.error('❌ Generation failed:', e.message);
  process.exit(1);
});
